CREATE DATABASE IF NOT EXISTS tarea_uziel CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tarea_uziel;

CREATE TABLE IF NOT EXISTS day_entries (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  entry_date DATE NOT NULL,
  title VARCHAR(120) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  image_data LONGBLOB NULL,
  image_mime VARCHAR(100) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_entry_date (entry_date)
);

CREATE TABLE IF NOT EXISTS app_settings (
  id TINYINT UNSIGNED NOT NULL,
  home_description TEXT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

INSERT INTO app_settings (id, home_description)
VALUES (1, '')
ON DUPLICATE KEY UPDATE id = id;